gougendou/work_from_home_ish

- app/controllers/workspaces_controller.rb
- app/models/workspace.rb
- app/views/workspaces/index.html.erb
- app/views/workspaces/show.html.erb
- config/routes.rb
- db/migrate/20230227123942_create_workspaces.rb
- db/schema.rb
- test/controllers/workspaces_controller_test.rb
- test/models/workspace_test.rb
added workspaces model, table in database and controller with index and show methods with empty views @AJM1994 @MPRevell @gougendou
> made workspaces model

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/models/user.rb
- app/views/devise/confirmations/new.html.erb
- app/views/devise/mailer/confirmation_instructions.html.erb
- app/views/devise/mailer/email_changed.html.erb
- app/views/devise/mailer/password_change.html.erb
- app/views/devise/mailer/reset_password_instructions.html.erb
- app/views/devise/mailer/unlock_instructions.html.erb
- app/views/devise/passwords/edit.html.erb
- app/views/devise/passwords/new.html.erb
- app/views/devise/registrations/edit.html.erb
- app/views/devise/registrations/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/devise/shared/_error_messages.html.erb
- app/views/devise/shared/_links.html.erb
- app/views/devise/unlocks/new.html.erb
- app/views/layouts/application.html.erb
- config/environments/development.rb
- config/initializers/devise.rb
- config/locales/devise.en.yml
- config/routes.rb
- db/migrate/20230227131451_devise_create_users.rb
- db/migrate/20230227140522_add_first_name_to_users.rb
- db/migrate/20230227140609_add_last_name_to_users.rb
- db/schema.rb
- test/models/user_test.rb
Added and migrated the user model with authentication
Schema can be found here https://kitt.lewagon.com/db/94045
> Adding the User model, with devise authentication implemented

- config/routes.rb
- db/schema.rb
The routing at the moment is broken because of the user devise. This should have fixed it
> fixing routing

- db/schema.rb
> schema changes

- Gemfile
- Gemfile.lock
- db/seeds.rb
> Added Seeds

- app/assets/stylesheets/components/_cards.scss
- app/controllers/workspaces_controller.rb
- app/views/layouts/application.html.erb
- app/views/workspaces/index.html.erb
I've put all cards that we should need across the app in the components file, I have also added experimental CSS to the index page for workspaces
> added components for cards and have also added CSS for the index page

- Gemfile.lock
- app/views/layouts/application.html.erb
added navbar logic to end the user session
> adding navbar logic for the login / logout

- app/views/workspaces/show.html.erb
1. Updated background image
2. Remove h1 above the image
3. Changed workplace title tex
4. Updated price format to £
5. Updated placeholder dates
> updated the show page-3

- config/routes.rb
changed in the routes to make the index the default homepage
> re-directing the homepage to be the navigation page

- app/models/workspace.rb
- db/migrate/20230227164907_add_userid_to_workplaces.rb
- db/schema.rb
and added relavent belongs to and has many removing the old throughs
> added foreign key to workplaces

- app/views/layouts/application.html.erb
Changed Matt's HTML to add logic to the navbar to allow different login and logout sessions
> sorted out the login session logic

- app/views/layouts/application.html.erb
changed the href to "/workspaces" for the logo in the navbar
> added link back to homepage to desk logo

- app/views/layouts/application.html.erb
changed the navbar to include the dropdown logic for the sign-up scenario as well as the logout scenario
updated the else statement within the if to better handle the case when the user is not logged in (i.e. still showing the options in the dropdown)
> added the navbar logic to the sign up user flow

- app/controllers/workspaces_controller.rb
- app/views/workspaces/new.html.erb
- config/routes.rb
added workspaces create new and destroy methods with a new view
> made relevent workspaces methods and views

- app/controllers/workspaces_controller.rb
- app/views/workspaces/edit.html.erb
also added description to strong params was missing before
> added edit view and edit and create methods to controler

- app/views/workspaces/new.html.erb
I've the #new routes/view a simple form for adding a new listing, we need to incorporate photos and default value for booked.
> added simple new listing page for workspaces

- app/views/workspaces/new.html.erb
form now has the photos but not sure how to output the photos into html
> added photos to form

- app/views/layouts/application.html.erb
- app/views/shared/_flashes.html.erb
Added flashes to the application html to let a user know when they have signed in etc.
> Login fixes

- app/controllers/workspaces_controller.rb
needed photos it have an array because was giving errors
> fixing cloudinary bugs

- app/models/user.rb
- app/models/workspace.rb
will delete all relevent data when dependant data is removed
> added dependant destroy to all has manys

- app/controllers/workspaces_controller.rb
- app/views/workspaces/edit.html.erb
- app/views/workspaces/show.html.erb
can now delete and edit a listing
> added edit and delete links to index

- app/views/workspaces/index.html.erb
Index Page now looks more presentable, still changes to be made but wanted to push into Github before making too many changes.
> edited workspace view page so that it looks better than very basic

- app/assets/stylesheets/application.scss
- app/views/bookings/index.html.erb
- updated full index page for the bookings
> bookings index page

- app/controllers/workspaces_controller.rb
was not deleting bookings with workspace id when trying to delete that workspace now works
> changed delete to destroy should now work

- app/controllers/bookings_controller.rb
- app/controllers/workspaces_controller.rb
- app/views/workspaces/new.html.erb
- app/views/workspaces/show.html.erb
Added the booking form to the workspace page
> added the booking form to the workspace show view

- app/views/workspaces/show.html.erb
Changed the red green logic
Added a second decimal and "per day"
> Changed the details section of workspaces

- app/assets/stylesheets/application.scss
- app/views/workspaces/index.html.erb
quick change but fiddly. landing page sizing and gradient changed. new picture added.
> landing page background

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
- config/routes.rb
Removed the "new" from booking routes as it is now handled in the workspaces method
> fixed the bookings routing and the total cost of booking calculation

- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
Added the cancel booking button to the bookings card - no styling yet
> added the cancel booking method without any styling

- Gemfile
- Gemfile.lock
- app/controllers/workspaces_controller.rb
- app/javascript/controllers/index.js
- app/javascript/controllers/map_controller.js
- app/models/workspace.rb
- app/views/layouts/application.html.erb
- app/views/workspaces/index.html.erb
- config/initializers/geocoder.rb
- db/migrate/20230301112116_add_coordinates_to_workspaces.rb
- db/schema.rb
…lationships between booking and workspaces.
Let's review this in the morning and get the appropriate views working with it, believe I have finished the model and controller :) NEED TO CHECK IT ALL THOUGH
> Adding geocoding

- app/views/bookings/index.html.erb
- app/views/workspaces/index.html.erb
- app/views/workspaces/show.html.erb
- db/seeds.rb
> cloudinary now works but images are not sized correctly

- app/assets/stylesheets/components/_cards.scss
- app/controllers/bookings_controller.rb
- app/views/bookings/index.html.erb
Reverts gougendou/work_from_home_ish#54
> Revert "added the delete button"

- app/assets/stylesheets/application.scss
- app/controllers/workspaces_controller.rb
- app/views/workspaces/index.html.erb
- db/schema.rb
- db/seeds.rb
- package.json
- yarn.lock
please check seed changes. was having errors doing
> db:reset
> db:seed
.
> geocode updates, seed needs to be watched. bit of ui on home page.

- db/seeds.rb
now when we have the key error we can run db:seed and it will then automatically clear the database. will now do default images
> rails db:seed will now clear the database

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/config/_colors.scss
- app/javascript/controllers/index.js
- app/javascript/controllers/toggle_controller.js
- app/views/workspaces/index.html.erb
- added in button 
- made button position: sticky, centred
- added a javascript script to html and created a toggle function for the map
next steps
- sort out page order
> show map toggle

- app/controllers/reviews_controller.rb
- app/controllers/workspaces_controller.rb
- app/models/review.rb
- app/models/workspace.rb
- app/views/workspaces/index.html.erb
- app/views/workspaces/show.html.erb
- config/routes.rb
- db/migrate/20230303111215_create_reviews.rb
- db/schema.rb
- test/controllers/reviews_controller_test.rb
- test/models/review_test.rb
Have an overview but this gives us a very basic review form at the bottom of each workspace - now need to style it and potentially add AJAX if enough time.
> Adding review model and controller

- db/seeds.rb
> now seeds with lots of stuff
